openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local-host
  url: http://localhost:8090/v1
security:
- {}
tags:
- description: not yet ready
  name: ps
paths:
  /ps:
    post:
      operationId: createps
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ps'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ps'
          description: successful operation
      summary: Creates the data
      tags:
      - ps
      x-eov-operation-handler: controllers/PsController
  /ps/{psId}:
    delete:
      operationId: deleteps
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: psId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - ps
      x-eov-operation-handler: controllers/PsController
    get:
      operationId: getps
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: psId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ps'
          description: successful operation
      summary: Get the element
      tags:
      - ps
      x-eov-operation-handler: controllers/PsController
    put:
      operationId: updateps
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: psId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ps'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ps'
          description: successful operation
      summary: Updates the element
      tags:
      - ps
      x-eov-operation-handler: controllers/PsController
  /ps/getAll:
    get:
      operationId: getAllps
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ps'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - ps
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/PsController
components:
  schemas:
    ps:
      example:
        ptitle: ptitle
        _id: _id
      properties:
        _id:
          type: string
        ptitle:
          type: string
      required:
      - ptitle
      type: object
